# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aegis/projects/tinygl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aegis/projects/tinygl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aegis/projects/tinygl/CMakeFiles /Users/aegis/projects/tinygl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aegis/projects/tinygl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GLESv1_CM

# Build rule for target.
GLESv1_CM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GLESv1_CM
.PHONY : GLESv1_CM

# fast build rule for target.
GLESv1_CM/fast:
	$(MAKE) -f src/CMakeFiles/GLESv1_CM.dir/build.make src/CMakeFiles/GLESv1_CM.dir/build
.PHONY : GLESv1_CM/fast

#=============================================================================
# Target rules for targets named gears

# Build rule for target.
gears: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gears
.PHONY : gears

# fast build rule for target.
gears/fast:
	$(MAKE) -f src/examples/CMakeFiles/gears.dir/build.make src/examples/CMakeFiles/gears.dir/build
.PHONY : gears/fast

#=============================================================================
# Target rules for targets named mech

# Build rule for target.
mech: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mech
.PHONY : mech

# fast build rule for target.
mech/fast:
	$(MAKE) -f src/examples/CMakeFiles/mech.dir/build.make src/examples/CMakeFiles/mech.dir/build
.PHONY : mech/fast

#=============================================================================
# Target rules for targets named spin

# Build rule for target.
spin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spin
.PHONY : spin

# fast build rule for target.
spin/fast:
	$(MAKE) -f src/examples/CMakeFiles/spin.dir/build.make src/examples/CMakeFiles/spin.dir/build
.PHONY : spin/fast

#=============================================================================
# Target rules for targets named texobj

# Build rule for target.
texobj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 texobj
.PHONY : texobj

# fast build rule for target.
texobj/fast:
	$(MAKE) -f src/examples/CMakeFiles/texobj.dir/build.make src/examples/CMakeFiles/texobj.dir/build
.PHONY : texobj/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GLESv1_CM"
	@echo "... gears"
	@echo "... mech"
	@echo "... spin"
	@echo "... texobj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

